query image {
  image(id: 8) {
    id
    src
    product_id
  }
}

query images {
  images(offset: 10, limit: 8) {
    id
    src
    product_id
  }
}

mutation imageAdd {
	imageAdd(data:{src:"uneufheiuzfheziuhfiuezhfizehfz",product_id:1}) {
	  id
	}
}

mutation imageUpdate {
  imageUpdate(id:801,data:{src:"deuxufezhfhzeiufhezf",product_id:2})
}

mutation imageRemove{
  imageRemove(id:801)
}
mutation imageRemoveAll{
  imageRemoveAll
}